config/routes.rb
Rails.application.routes.draw do
  resources :links, only: [:index, :show, :create, :new]
  get '/:id' => 'links#show'
  get '/report' => 'links#index'

  root 'links#new'
end

app/models/link.rb
require "base64"
class Link < ActiveRecord::Base
  validates :destination, :format => URI::regexp(%w(http https))
  before_create :generate_slug

  def short_url
    "http://localhost:3000/#{self.slug}"
  end

  private

    def generate_slug
      letters =  self.destination.split.shuffle[0 .. 8].join
      self.slug = Base64.encode64(letters)[0,8]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find_by(slug: params[:id])
    if @link
      @link.count =  @link.count + 1
      @link.save
      redirect_to @link.destination
    else
      redirect_to root_url
    end
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.count = 0 #cheat and always start at 0
    if @link.save
      flash[:info] = @link.short_url
      redirect_to root_url
    end
  end

  # GET /links/new
  def new
    @link = Link.new
  end




  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:slug, :destination, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortnr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |key, msg| %>
    <h2><%= msg %></h2>
  <% end %>
<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination, "Url to shorten" %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit "Shorten" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Slug</th>
      <th>Destination</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.slug %></td>
        <td><%= link.destination %></td>
        <td><%= link.count %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slug:</strong>
  <%= @link.slug %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @link.destination %>
</p>

<p>
  <strong>Count:</strong>
  <%= @link.count %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>